#!/bin/sh

echo "---------------------------------------------------"
echo
echo -n "New Hostname?"
read hostname
sudo hostnamectl set-hostname $hostname

echo "---------------------------------------------------"
echo
echo -n "Username?"
read username
echo -n "New Password?"
read password
sudo passwd $username $password

sudo reboot
