#!/bin/sh

sudo apt update
sudo apt upgrade -y

sudo apt update
sudo apt install -y fail2ban
sudo systemctl start fail2ban
sudo systemctl enable fail2ban

sudo apt update
sudo apt install -y clamav clamav-daemon
sudo systemctl stop clamav-freshclam
sudo freshclam
sudo mkdir /var/lib/clamav
sudo systemctl start clamav-freshclam

sudo apt install -y unattended-upgrades
sudo /etc/init.d/unattended-upgrades start

sudo apt install  avrdude -y

echo "Installation done"
echo "Beginning Configuration"

echo "---------------------------------------------------"
echo "Host Settings"
echo "---------------------------------------------------"
while true; do
    read -p "Do you want to change the hostname?" yn
    case $yn in
        [Yy]* ) read -p "New Hostname?" host; sudo hostname $host; echo "hostname changed succesfully"; break;;
        [Nn]* ) break;;
        * ) echo "Please answer yes or no.";;
    esac
done
while true; do
    read -p "Do you want to change the password?" yn
    case $yn in
        [Yy]* ) read -p "New Password?" psw; sudo passwd $psw; echo "password changed succesfully"; break;;
        [Nn]* ) break;;
        * ) echo "Please answer yes or no.";;
    esac
done

echo "---------------------------------------------------"
echo "Internet Settings"
echo "---------------------------------------------------"
echo -n "Interface"
read iface
echo -n "Static IP?"
read IP
echo -n "Subnet Mask?"
read mask
echo -n "Gateway?"
read GW
echo 'interface $iface' >> /etc/dhcpcd.conf
echo 'static ip_address=$IP/$mask' >> /etc/dhcpcd.conf
echo 'static routers=$GW' >> /etc/dhcpcd.conf
echo 'static domain_name_servers=$GW 8.8.8.8' >> /etc/dhcpcd.conf
echo 'interface $iface' >> /etc/dhcpcd.conf

sudo reboot
